### ISSUE TITLE
Test noncompiled code

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/Algebroids#95]
@zickgraf: Like with `SkeletalFinSets`, I would also be interested in testing the noncompiled code here as well.

**Comment by zickgraf** [comment]
Applying a current version of `PackageJanitor` (https://github.com/homalg-project/PackageJanitor/commit/2a3a1acca786738c2af7dd4c537869ba17d7c368) should suffice.

**Comment by mohamed-barakat** [comment]
Ah, wonderful.
